config/routes.rb
Rails.application.routes.draw do
  get 'reservations/:id/braintree/new' => 'braintree#new', as: :braintree_new
  post 'reservations/:id/braintree/checkout' => 'braintree#checkout', as: :braintree_checkout

  get 'home/index'

  resources :listings, only: [:index, :show]
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :searches

  resources :users, controller: "users", only: [:create, :edit, :update] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
    resources :listings do
      resources :reservations
    end    
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
end

app/models/listing.rb
class Listing < ApplicationRecord
	belongs_to :user
	mount_uploaders :photos, PhotoUploader
	has_many :reservations
 

	PLACE_TYPE_OPTIONS = [ "Landed", "Condo", "Apartment"]

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	
	def index
		x = params[:search]
		id = params[:user_id]
		if x
			@listings = Listing.where(["name LIKE ?", "%#{params[:search]}%"]).order(:name).page(params[:page]).per(10)
		else
			if id
				@listings = current_user.listings.order(:name).page(params[:page]).per(10)
			else
				@listings = Listing.order(:name).page(params[:page]).per(10)
			end
		end
	end

	def new
		@listing = Listing.new
	end

	def create
		@listing = current_user.listings.new(listing_params)
		
		if @listing.save
			redirect_to root_url
		else
			redirect_to new_user_listing_path(current_user.id)
		end
	end

	def show
		id = params[:id]
		@listing = Listing.find(id)
	end

	def edit
		id = params[:id]
		@listing = Listing.find(id)
	end

	def update
		id = params[:id]
		@listing = Listing.find(id)
			if @listing.update_attributes(listing_params)
				redirect_to listing_path(@listing.id)
			else
				redirect_to edit_user_listing_path(@listing.id)
			end
	end

	private 

	def listing_params
		params.require(:listing).permit(:name, :place_type, :property_type, :price, {photos: []})
	end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for [current_user, @listing] do |form| %>

	<div>
	  <%= form.label :photos %>
	  <%= form.file_field :photos, multiple: true %>
	</div>
	
	<div>
		<%= form.label :name %>
		<%= form.text_field :name %> 
	</div>

	<div>
	  <%= form.label :place_type %>
	  <%= form.select :place_type, options_for_select(Listing::PLACE_TYPE_OPTIONS) %>
	</div>

	<div>
	  <%= form.label :property_type %>
	  <%= form.text_field :property_type %> 
	</div>

	<div>
	  <%= form.label :price %>
	  <%= form.text_field :price %> 
	</div>

	<div class="submit-field">
	  <%= form.submit %>
	</div>
<% end %>

app/views/listings/edit.html.erb
<h1>Edit listing for <%= @listing.name%></h1>

<%= render partial: '/listings/form'%>

<div><%= link_to "My Listing", user_listings_path(current_user.id)%></div>
<div> <%= link_to "All Listings", listings_path%></div>
<div><%= link_to "Home", home_index_path%></div>

app/views/listings/index.html.erb
<table>
	<tr>
		<th>No.</th>
		<th>Name</th>
		<th>Address</th>
	</tr>
<% @listings.each do |x| %>
	<tr>
		<td> <%= x.id=%> </td>
		<td> <%= link_to x.name, listing_path(x.id) %> </td>
		<td> <%= x.address=%> </td>
	</tr>
<% end %>

</table>

<%= paginate @listings %>
<%= page_entries_info @listings%>

<div><%= link_to "Home", home_index_path%></div>

app/views/listings/new.html.erb
<h1>Create new listing for <%= current_user.name%></h1>

<%= render partial: '/listings/form'%>

<%= link_to "Home", home_index_path%>

<!-- t.string :name
t.string :place_type
t.string :property_type
t.integer :guest_number
t.string :country
t.string :state
t.string :city
t.integer :zipcode
t.string :address
t.integer :price
t.string :description -->

app/views/listings/show.html.erb
<h1>Listing: <%= @listing.name %></h1>


<% @listing.photos.each do |photo| %>
	<span><%= image_tag photo.thumb.to_s %></span>
<%end%>
<%#byebug%>
<div>Place type: <%= @listing.place_type %></div>

<%if @listing.user_id == current_user.id %>
	<p><%= link_to "Edit Listing", edit_user_listing_path(@listing.id) %></p>	
<% else %>
	<p><%= link_to "BOOK THIS PROPERTY", new_user_listing_reservation_path(user_id: current_user.id, listing_id: @listing.id) %></p>
<%end%>
<div><%= link_to "My Listings", user_listings_path(current_user.id)%></div>
<div> <%= link_to "All Listings", listings_path%></div>
<p><%= link_to "Home", home_index_path%></p>