config/routes.rb
Rails.application.routes.draw do
  get 'reservations/:id/braintree/new' => 'braintree#new', as: :braintree_new
  post 'reservations/:id/braintree/checkout' => 'braintree#checkout', as: :braintree_checkout

  get 'home/index'

  resources :listings, only: [:index, :show]
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :searches

  resources :users, controller: "users", only: [:create, :edit, :update] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
    resources :listings do
      resources :reservations
    end    
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  # include Clearance::User

  has_many :authentications, dependent: :destroy
  mount_uploader :avatar, AvatarUploader
  has_many :listings, dependent: :destroy
  has_many :reservations
   

  def self.create_with_auth_and_hash(authentication, auth_hash)
    user = self.create!(
      name: auth_hash["extra"]["raw_info"]["name"],
      email: auth_hash["extra"]["raw_info"]["email"],
      password: SecureRandom.hex(5) 
      # rand(36**9).to_s(36)
    )
    user.authentications << authentication
    return user
  end

  # grab fb_token to access Facebook for user data
  def fb_token
    x = self.authentications.find_by(provider: 'facebook')
    return x.token unless x.nil?
  end

end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
	
	def edit
		@user = User.find(current_user.id)
	end

	def create
		@user = User.new(user_params)
		if @user.save
			sign_in(@user)
			redirect_to root_url
		else
			redirect_to sign_up_path
		end
	end

	def update
		@user = User.find(current_user.id)
			if @user.update_attributes(user_params)
				redirect_to root_path
			else
				redirect_to edit_user_path(current_user.id)
			end
	end

	private 

	def user_params
		params.require(:user).permit(:name, :email, :password, :avatar)
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div>
  <%= form.label :avatar %>
  <%= form.file_field :avatar, class: "form-control" %>
</div>

<div class="text-field">
  <%= form.label :name %>
  <%= form.text_field :name, type: 'name' %>
</div>

<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%#= form.label :password %>
  <%#= form.password_field :password %>
</div>

app/views/users/edit.html.erb
<h1>Edit Your Profile</h1>
<p><%= image_tag current_user.avatar.thumb.to_s %></p>
<%= form_for @user do |form| %>
<%= render partial: '/users/form', object: form %> 

<div class="submit-field">
  <%= form.submit %>
</div>

<% end %>

<%= link_to "Home", home_index_path%>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="password-field">
      <%= form.label :password %>
      <%= form.password_field :password %>
    </div>
    
    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>