config/routes.rb
Rails.application.routes.draw do
  get 'reservations/:id/braintree/new' => 'braintree#new', as: :braintree_new
  post 'reservations/:id/braintree/checkout' => 'braintree#checkout', as: :braintree_checkout

  get 'home/index'

  resources :listings, only: [:index, :show]
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :searches

  resources :users, controller: "users", only: [:create, :edit, :update] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
    resources :listings do
      resources :reservations
    end    
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  	if current_user
  		@user = User.find(current_user.id)
  	end
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Pairbnb Homepage</h1>

<% if current_user %>
<h2> Welcome <%= link_to User.find(current_user.id).name, root_path %> </h2>
<p><%= image_tag current_user.avatar.thumb.to_s %></p>
<div><%= link_to "Create new listing", new_user_listing_path(current_user.id)%></div>
<div><%= link_to "My Listings", user_listings_path(current_user.id)%></div>
<div> <%= link_to "Edit Profile", edit_user_path(current_user.id) %> </div>
<% end %>


<div> <%= link_to "All Listings", listings_path%></div>

<div>
   <%= form_tag listings_path, :method => 'get' do %>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search" %>
   <% end %>

</div>

<% if current_user %>
    <% @user.listings.each do |listing| %>

    	<div>
    	<span><%= listing.name%> </span>
    	<% listing.photos.each do |photo| %>
    		<span><%= link_to (image_tag photo.thumb.to_s), listing_path(listing.id.to_i) %></span>
    	<%end%>
    	</div>
    <%end%>
    <h3>My Reservations</h3>
    <% r = Reservation.where(user_id: current_user.id) %>
    <% r.each do |x| %>

        <div>
        <% l = Listing.find(x.listing_id) %>    
        <span><%= l.name%> </span>
        <% l.photos.each do |photo| %>
            <span><%= link_to (image_tag photo.thumb.to_s), listing_path(l.id.to_i) %></span>
        <%end%>
        <span><%= x.start_date %></span>
        <span> __ </span>
        <span><%= x.end_date %></span>
        <span> __ </span>
        <span><%= x.duration %> days</span>
        <span> __ </span>
        <span><%= link_to "Delete", user_listing_reservation_path(current_user,l,x), method: :delete %></span>
        </div>
    <%end%>
<% end %>
<!-- <div class="container">
    <div class="row">
        <div class='col-sm-6'>
            <div class="form-group">
                <div class='input-group date' id='datetimepicker1'>
                    <input type='text' class="form-control" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker();
            });
        </script>
    </div>
</div>

 -->